CREATE DATABASE biblioteca
WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

--------------------------------------------------------------------------------
-------------------------------------TABLAS-------------------------------------

-----País
CREATE SEQUENCE sq_paiid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Pais(
paiId INTEGER DEFAULT nextval('sq_paiid'::regclass) CONSTRAINT PK_paiId PRIMARY KEY,
paiAbrev CHARACTER VARYING(10),
paiNombre CHARACTER VARYING(50)
);

-----Configuración
CREATE SEQUENCE sq_cfgid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Configuracion(
cfgId INTEGER DEFAULT nextval('sq_cfgid'::regclass) CONSTRAINT PK_cfgId PRIMARY KEY,
cfgNombre CHARACTER VARYING(50) NOT NULL,
cfgDireccion CHARACTER VARYING(250),
cfgTelefono1 CHARACTER VARYING(10),
cfgTelefono2 CHARACTER VARYING(10),
cfgMora numeric(4,4),
cfgMaxPrestamos SMALLINT,
cfgPermitReserva BOOLEAN CONSTRAINT DF_cfgPermitReserva DEFAULT 'T',
paiId INTEGER CONSTRAINT FK_Pais_Configuracion REFERENCES Pais(paiId)
);

-----Idioma
CREATE SEQUENCE sq_langid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Idioma(
langId INTEGER DEFAULT nextval('sq_langid'::regclass) CONSTRAINT PK_langId PRIMARY KEY,
langAbrev CHARACTER VARYING(10),
langNombre CHARACTER VARYING(50)
);

-----Editorial
CREATE SEQUENCE sq_edtid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Editorial(
edtId INTEGER DEFAULT nextval('sq_edtid'::regclass) CONSTRAINT PK_edtId PRIMARY KEY,
edtCodigo CHARACTER VARYING(10) CONSTRAINT UQ_edtCodigo UNIQUE,
edtNombre CHARACTER VARYING(50) NOT NULL,
edtTelefono CHARACTER VARYING(20),
edtDireccion CHARACTER VARYING(1500),
paiId INTEGER CONSTRAINT FK_Pais_Editorial REFERENCES Pais(paiId)
);

INSERT INTO editorial (edtcodigo, edtnombre, edttelefono, edtdireccion, paiid) VALUES(null,'Editorial EDISAL S.A. de C.V.','22607525','7 Calle poniente, entre 75 [...]',67);
----------------------------Calcular el código de editorial
CREATE OR REPLACE FUNCTION calc_edtCodigo() RETURNS TRIGGER AS
$BODY$
BEGIN
	NEW.edtCodigo := 'EDT'||(SELECT last_value FROM sq_edtid)||NEW.paiid;
	RETURN NEW;
END;
$BODY$ LANGUAGE plpgsql

CREATE TRIGGER calc_edtCodigo
BEFORE INSERT ON editorial FOR EACH ROW EXECUTE PROCEDURE calc_edtCodigo();

-----Autor
CREATE SEQUENCE sq_autid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Autor(
autId INTEGER DEFAULT nextval('sq_autid'::regclass) CONSTRAINT PK_autId PRIMARY KEY,
autNombre CHARACTER VARYING(50) NOT NULL,
autApellido CHARACTER VARYING(50) NOT NULL,
autFechaNac DATE,
paiId INTEGER CONSTRAINT FK_Pais_Autor REFERENCES Pais(paiId)
);

-----TipoProducto (libro, revista, etc.)
CREATE SEQUENCE sq_tproid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE TipoProducto(
tproId INTEGER DEFAULT nextval('sq_tproid'::regclass) CONSTRAINT PK_tproId PRIMARY KEY,
tproCodigo CHARACTER VARYING(10) CONSTRAINT UQ_tproCodigo UNIQUE,
tproAbrev CHARACTER VARYING(15),
tproNombre CHARACTER VARYING(30) NOT NULL
);


-----CategoriaProducto
CREATE SEQUENCE sq_cproid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE CategoriaProducto(
cproId INTEGER DEFAULT nextval('sq_cproid'::regclass) CONSTRAINT PK_cproId PRIMARY KEY,
cproCodigo CHARACTER VARYING(10) CONSTRAINT UQ_cproCodigo UNIQUE,
cproIdPrin INTEGER CONSTRAINT FK_CatgoriaProducto_CategoriaProducto REFERENCES CategoriaProducto(cproId),
cproNombre CHARACTER VARYING(350) NOT NULL
);

-----Libro
CREATE SEQUENCE sq_proid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Producto(
proId INTEGER DEFAULT nextval('sq_proid'::regclass) CONSTRAINT PK_proId PRIMARY KEY,
tproId INTEGER CONSTRAINT FK_tipoProducto_Producto REFERENCES TipoProducto(tproId),
cproId INTEGER CONSTRAINT FK_CategoriaProducto_Producto REFERENCES CategoriaProducto(cproId),
proIsbnIssn INTEGER NOT NULL CONSTRAINT UQ_proIsbnIssn UNIQUE,
proCodigo CHARACTER VARYING(10) NOT NULL CONSTRAINT UQ_proCodigo UNIQUE,
proNombre CHARACTER VARYING(500) NOT NULL,
proEdicion SMALLINT,
edtId INTEGER CONSTRAINT FK_Editorial_Producto REFERENCES Editorial(edtId),
proNumpagina INTEGER,
proPublicLugar CHARACTER VARYING(50),
proPublicAnio INTEGER,
proVolumen SMALLINT,
proNumEjemplar SMALLINT,
proEmpastado CHARACTER VARYING(50),
proPeso SMALLINT,
proColeccion CHARACTER VARYING(50),
langId INTEGER CONSTRAINT FK_Idioma_Libro REFERENCES Idioma(langId),
proDescripcion CHARACTER VARYING(3500)
);


-----LibroAutor
CREATE SEQUENCE sq_proautid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE ProductoAutor(
proautId INTEGER DEFAULT nextval('sq_proautid'::regclass) CONSTRAINT PK_proautId PRIMARY KEY,
proId INTEGER CONSTRAINT FK_Producto_ProductoAutor REFERENCES Producto(proId),
autId INTEGER CONSTRAINT FK_Autor_ProductoAutor REFERENCES Autor(autId)
);

-----Materias
CREATE SEQUENCE sq_matid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Materia(
matId INTEGER DEFAULT nextval('sq_matid'::regclass) CONSTRAINT PK_matId PRIMARY KEY,
matCodigo CHARACTER VARYING(10) CONSTRAINT UQ_matCodigo UNIQUE,
matIdPrin INTEGER CONSTRAINT FK_Materia_Materia REFERENCES Materia(matId),
matNombre CHARACTER VARYING(50) NOT NULL
);

-----LibroMateria
CREATE SEQUENCE sq_prodmatid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE ProductoMateria(
promatId INTEGER DEFAULT nextval('sq_prodmatid'::regclass) CONSTRAINT PK_promatId PRIMARY KEY,
proId INTEGER CONSTRAINT FK_Producto_ProductoMateria REFERENCES Producto(proId),
matId INTEGER CONSTRAINT FK_Materia_ProductoMateria REFERENCES Materia(matId)
);

-----EstadoLibro
CREATE SEQUENCE sq_stpid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE EstadoProducto(
stpId INTEGER DEFAULT nextval('sq_stpid'::regclass) CONSTRAINT PK_stpId PRIMARY KEY,
stpEstado CHARACTER VARYING(30) NOT NULL
);

-----Copias
CREATE SEQUENCE sq_cpid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Copia(
cpId INTEGER DEFAULT nextval('sq_cpid'::regclass) CONSTRAINT PK_cpId PRIMARY KEY,
proId INTEGER CONSTRAINT FK_Producto_Copia REFERENCES Producto(proId),
cpUbicacion CHARACTER VARYING(30),
cfgId INTEGER NOT NULL CONSTRAINT FK_Configuracion_Copia REFERENCES Configuracion(cfgId),
stpId INTEGER CONSTRAINT FK_EstadoProducto_Copia REFERENCES EstadoProducto(stpId)
);

-----Saldo
CREATE SEQUENCE sq_sldid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Saldo(
sldId INTEGER DEFAULT nextval('sq_sldid'::regclass) CONSTRAINT PK_sldId PRIMARY KEY,
proId INTEGER CONSTRAINT FK_Producto_Saldo REFERENCES Producto(proId),
sldTotal INTEGER NOT NULL CONSTRAINT DF_sldTotal DEFAULT 0 CONSTRAINT CK_sldTotal CHECK(sldTotal >= 0), --total cantidad Producto
sldReserva INTEGER NOT NULL CONSTRAINT DF_sldreserva DEFAULT 0 CONSTRAINT CK_sldReserva CHECK (sldReserva >= 0), --saldo de reserva
sldPrestamo INTEGER NOT NULL CONSTRAINT DF_sldPrestamo DEFAULT 0 CONSTRAINT CK_sldPrestamo CHECK (sldPrestamo >= 0), --saldo de prestamo
sldSaldo INTEGER CONSTRAINT DF_sldSaldo DEFAULT 0 CONSTRAINT CK_sldSaldo CHECK (sldSaldo >= 0), -- saldo (total - prestamo - reserva)
cfgId INTEGER NOT NULL CONSTRAINT FK_configuracion_saldo REFERENCES Configuracion(cfgId)
);

----------------------------Convertir a campo calculado sldtotal
CREATE OR REPLACE FUNCTION calc_func_sldtotal() RETURNS TRIGGER AS
$BODY$
BEGIN
	IF(TG_OP = 'UPDATE') THEN
		UPDATE saldo SET sldsaldo = OLD.sldsaldo - NEW.sldreserva;
	END IF;
	NEW.sldtotal := NEW.sldsaldo - NEW.sldreserva;
	RETURN NEW;
END;
$BODY$ LANGUAGE plpgsql

CREATE TRIGGER calc_trg_sldtotal
BEFORE INSERT OR UPDATE ON saldo FOR EACH ROW EXECUTE PROCEDURE calc_func_sldtotal();

----------------------------

-----TipoUsuario
CREATE SEQUENCE sq_tusrid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE TipoUsuario(
tusrId INTEGER DEFAULT nextval('sq_tusrid'::regclass) CONSTRAINT PK_tusrId PRIMARY KEY,
tusrAbrev CHARACTER VARYING(10),
tusrNombre CHARACTER VARYING(50)
);

INSERT INTO TipoUsuario(tusrAbrev,tusrNombre) VALUES('admin','Administrador');
INSERT INTO TipoUsuario(tusrAbrev,tusrNombre) VALUES('est','Estudiante');

-----Usuario
CREATE SEQUENCE sq_usrid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Usuario(
usrId INTEGER DEFAULT nextval('sq_usrid'::regclass) CONSTRAINT PK_usrId PRIMARY KEY,
usrCodigo CHARACTER VARYING(10) CONSTRAINT UQ_usrCodigo UNIQUE,
usrNombre CHARACTER VARYING(50),
usrApellido CHARACTER VARYING(50),
tusrId INTEGER CONSTRAINT FK_TipoUsuario_Usuario REFERENCES TipoUsuario(tusrId),
usrPass CHARACTER VARYING(64)
);

INSERT INTO Usuario(usrCodigo,usrNombre,usrApellido,tusrId,usrPass) VALUES('RM132133','Luis Eduardo','Rivera Martínez',1,
'0208788aa2035cd5be6697efbd285df1afa881c8fd25e4bd5bbb247c29c58454');
-----Préstamo
CREATE SEQUENCE sq_prstid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Prestamo(
prstId INTEGER DEFAULT nextval('sq_prstid'::regclass) CONSTRAINT PK_prstid PRIMARY KEY,
prstFechaPres TIMESTAMP CONSTRAINT DF_prstfechapres DEFAULT NOW(), --Fecha de prestamo
prstFechaPrevDev TIMESTAMP CONSTRAINT CK_prstfechaprevdev CHECK(prstfechaprevdev >= prstfechapres), --Fecha prevista a devolucion
prstFechaDev TIMESTAMP CONSTRAINT CK_prstfechadev CHECK(prstfechadev >= prstfechapres), --Fecha de devolucion
usrId INTEGER CONSTRAINT FK_usuario_prestamo REFERENCES usuario(usrid),
proId INTEGER CONSTRAINT FK_Producto_prestamo REFERENCES Producto(proid),
prstMora DECIMAL(4,4) CONSTRAINT DF_prsmora DEFAULT 0.0,
prstDev BOOLEAN CONSTRAINT DF_prstdev DEFAULT 'F',
cfgId INTEGER NOT NULL CONSTRAINT FK_configuracion_prestamo REFERENCES configuracion(cfgid)
);

-----Reserva
CREATE SEQUENCE sq_rsvid INCREMENT 1 START 1 MINVALUE 1;

CREATE TABLE Reserva(
rsvId INTEGER DEFAULT nextval('sq_prstid'::regclass) CONSTRAINT PK_rsvtId PRIMARY KEY,
rsvFechaReserva TIMESTAMP CONSTRAINT DF_rsvFechaReserva DEFAULT NOW(),
rsvFechaRetiro TIMESTAMP CONSTRAINT CK_rsvFechaRetiro CHECK(rsvFechaRetiro >= rsvFechaReserva),
usrId INTEGER CONSTRAINT FK_Usuario_Prestamo REFERENCES Usuario(usrId),
proId INTEGER CONSTRAINT FK_Producto_Prestamo REFERENCES Producto(proId),
cfgId INTEGER NOT NULL CONSTRAINT FK_Configuracion_Prestamo REFERENCES Configuracion(cfgId)
);


--------------------------------------------------------------------------------
------------------------------------FUNCIONES-----------------------------------

-----Agregar editorial
CREATE OR REPLACE FUNCTION addeditorial(t_edtnombre editorial.edtnombre%TYPE, t_edttelefono editorial.edttelefono%TYPE, t_edtdireccion editorial.edtdireccion%TYPE, t_paiid editorial.paiid%TYPE)
RETURNS TEXT AS $BODY$ BEGIN
	IF (SELECT COUNT(edtnombre) FROM editorial WHERE edtnombre = t_edtnombre) = 0 THEN
		INSERT INTO editorial(edtcodigo,edtnombre,edttelefono,edtdireccion,paiid) VALUES('EDT'||(SELECT last_value FROM sq_edtid),t_edtnombre,t_edttelefono,t_edtdireccion,t_paiid);
	ELSE
		RAISE EXCEPTION 'El nombre de la editorial % ya existe', t_edtnombre;
	END IF;
	RETURN (SELECT 'EDT'||(SELECT last_value FROM sq_edtid)::CHARACTER VARYING AS codigo);
END;
$BODY$ LANGUAGE plpgsql;

-----Agregar autor
CREATE OR REPLACE FUNCTION addautor(t_autnombre autor.autnombre%TYPE, t_autapellido autor.autapellido%TYPE, t_autfechanac autor.autfechanac%TYPE, t_paiid autor.paiid%TYPE)
RETURNS TEXT AS $BODY$ BEGIN
	IF (SELECT COUNT(autid) FROM autor WHERE autnombre = t_autnombre AND autapellido = t_autapellido) = 0 THEN
		INSERT INTO autor(autnombre,autapellido,autfechanac,paiid) VALUES(t_autnombre,t_autapellido,t_autfechanac,t_paiid);
	ELSE
		RAISE EXCEPTION 'El autor % % ya existe', t_autnombre, t_autapellido;
	END IF;
	RETURN (SELECT (t_autnombre || " " || t_autapellido)::CHARACTER VARYING AS nombre);
END;
$BODY$ LANGUAGE plpgsql;

-----Agregar producto
CREATE OR REPLACE FUNCTION addProducto(t_tproid Producto.tproid%TYPE,t_cproid Producto.cproid%TYPE,t_proisbnissn Producto.proisbnissn%TYPE,t_pronombre Producto.pronombre%TYPE,
t_proedicion Producto.proedicion%TYPE,t_edtid Producto.edtid%TYPE,t_pronumpagina Producto.pronumpagina%TYPE,t_propubliclugar Producto.propubliclugar%TYPE,
t_propublicanio Producto.propublicanio%TYPE,t_provolumen Producto.provolumen%TYPE,t_pronumejemplar Producto.pronumejemplar%TYPE,t_proempastado Producto.proempastado%TYPE,
t_propeso Producto.propeso%TYPE,t_procoleccion Producto.procoleccion%TYPE,t_langid Producto.langid%TYPE,t_proDescripcion Producto.proDescripcion%TYPE,
t_autid CHARACTER VARYING(20))
RETURNS TEXT AS $BODY$
DECLARE
	codigo Producto.procodigo%TYPE; rec RECORD; cur CURSOR FOR (SELECT re FROM regexp_split_to_table(t_autid, ',') AS re);
	maximo INTEGER;
BEGIN
    	--ID: tipoProducto - categoriaProducto - correlativo
	/*codigo := t_cproid || '-' || (SELECT MAX(split_part(lbrcodigo,'-',3)) FROM libro WHERE lbrcodigo LIKE (t_cfid || '-' || tlbrid || '-%'));
	INSERT INTO libro(tlbrid,lbrisbn,lbrcodigo,lbrtitulo,lbredicion,edtid,lbrnumpagina,lbrpubliclugar,lbrpublicanio,lbrvolumen,lbrnumejemplar,lbrempastado,lbrpeso,lbrcoleccion,langid,lbrDescripcion,lbrestante)
		VALUES(t_tlbrid,t_lbrisbn,codigo,t_lbrtitulo,t_lbredicion,t_edtid,t_lbrnumpagina,t_lbrpubliclugar,t_lbrpublicanio,t_lbrvolumen,t_lbrnumejemplar,t_lbrempastado,t_lbrpeso,t_lbrcoleccion,t_lbrDescripcion,t_lbrestante);*/

	maximo := (SELECT MAX(procodigo::INTEGER) FROM producto WHERE cproid = t_cproid);
	IF(maximo > 0) THEN
		codigo := (maximo + 1);
	ELSE
		codigo := t_cproid || '100';
	END IF;
	--codigo := (SELECT cprocodigo FROM categoriaProducto WHERE cproid = t_cproid) || '-' || (SELECT MAX(split_part(procodigo,'-',2)) FROM Producto WHERE cproid = t_cproid);
	INSERT INTO Producto(tproid,cproid,proisbnissn,procodigo,pronombre,proedicion,edtid,pronumpagina,propubliclugar,propublicanio,provolumen,pronumejemplar,proempastado,propeso,procoleccion,langid,prodescripcion)
		VALUES(t_tproid,t_cproid,t_proisbnissn,codigo,t_pronombre,t_proedicion,t_edtid,t_pronumpagina,t_propubliclugar,t_propublicanio,t_provolumen,t_pronumejemplar,t_proempastado,t_propeso,t_procoleccion,t_langid,t_prodescripcion);

	OPEN cur;
	LOOP
		FETCH cur INTO rec;
		EXIT WHEN NOT FOUND;
		INSERT INTO Productoautor(proid,autid) VALUES((SELECT last_value FROM sq_proid), rec.re::INTEGER);
	END LOOP;
	CLOSE cur;
	RETURN (SELECT codigo::INTEGER AS codigo);
END;
$BODY$ LANGUAGE plpgsql;

select re from regexp_split_to_table('2,01,3957', ',') AS re;
select split_part('2-01-3957','-',3) WHERE '2-01-3957' LIKE ('2' || '-' || '01' || '-%');

-----Copias
CREATE OR REPLACE FUNCTION addCopias(t_proId copia.proId%TYPE,t_cpUbicacion copia.cpUbicacion%TYPE,t_numCopias INTEGER,t_cfgId copia.cfgId%TYPE)
RETURNS TEXT AS $BODY$
DECLARE
	codigo CHARACTER VARYING(250);
BEGIN
	FOR i IN 1..t_numCopias LOOP
		INSERT INTO Copia(proId,cpUbicacion,cfgId) VALUES(t_proId,t_cpUbicacion,t_cfgId);
		IF (i > 1) THEN
			codigo := codigo || ', ' || (SELECT last_value FROM sq_cpId);
		ELSE
			codigo := (SELECT last_value FROM sq_cpId);
		END IF;
	END LOOP;
	RETURN (SELECT codigo::CHARACTER VARYING AS codigo);
END;
$BODY$ LANGUAGE plpgsql;



-----Prestamo
CREATE OR REPLACE FUNCTION prestamo(t_prstid prestamo.prstid%TYPE,t_prstfechapres prestamo.prstfechapres%TYPE,t_prstfechaprevdev prestamo.prstfechaprevdev%TYPE,t_prstfechadev prestamo.prstfechadev%TYPE,
t_usrid prestamo.usrid%TYPE,t_lbrid prestamo.lbrid%TYPE,t_prstdev prestamo.prstdev%TYPE,t_cfgid prestamo.cfgid%TYPE,operacion CHARACTER VARYING(10)) RETURNS VOID AS $BODY$
BEGIN
	CASE
		WHEN(operacion = "INSERT") THEN
			IF((SELECT sldsaldo FROM saldo WHERE lbrid = t_lbrid) > 0) THEN --Verifica disponibilidad del libro
				IF((SELECT COUNT(prstid) FROM prestamo WHERE usrid = t_usrid AND prsetdev = 'F') < (SELECT cfgmaxprestamos FROM configuracion)) THEN
				--Verifica si no ha excedido el límite de prestamos
					IF((SELECT SUM(prstmora) AS mora FROM prestamo WHERE usrid = t_usrid AND prsetdev = 'F') > 0.0) THEN
						RAISE EXCEPTION 'El usuario tiene mora pendiente';
					ELSE
						INSERT INTO prestamo(prstfechaprevdev,usrid,lbrid,cfgid) VALUES(now() + interval '1 day',t_usrid,t_lbrid,t_cfgid);
					END IF;
				ELSE
					RAISE EXCEPTION 'El usuario ha excedido el límite de prestamos';
				END IF;
			ELSE
				RAISE EXCEPTION 'El libro no está disponible en este lugar';
			END IF;
		WHEN(operacion = "RENADM") THEN --renovacion encargard/a de biblioteca
			UPDATE prestamo SET prstfechaprevdev = t_prstfechaprevdev WHERE prstid = t_prstid;
		WHEN(operacion = "PAGO") THEN --pago de mora
			UPDATE prestamo SET prsmora = 0.0 WHERE prstid = t_prstid;
		WHEN(operacion = "RENUSR") THEN --renovación por el usuario
			UPDATE prestamo SET prstfechaprevdev = (now() + interval '1 day') WHERE prstid = t_prstid;
		ELSE --devolucion
			UPDATE prestamo SET prstfechadev = now(), prstdev = 'T' WHERE prstid = t_prstid;
			UPDATE saldos SET sldsaldo = sldsaldo + 1 WHERE lbrid = t_lbrid AND cfgid = t_cfgid;
	END CASE;
END;
$BODY$ LANGUAGE plpgsql;

--------------------------------------------------------------------------------
--------------------------------INSERTANDO DATOS--------------------------------

INSERT INTO Idioma(langAbrev,langNombre) VALUES('es','ESPAÑOL'),('en','INGLES'),('fr','FRANCES'),('pt','PORTUGUES');

INSERT INTO TipoProducto(tproAbrev,tproNombre) VALUES('LBR','LIBRO'),('REV','REVISTA'),('TES','TESIS'),('CD','CD'),('DVD','DVD'),('PLN','PLANO'),('MAP','MAPA');

INSERT INTO Configuracion(cfgNombre,cfgDireccion,cfgTelefono1,cfgMora,cfgMaxPrestamos,cfgPermitReserva,paiId) VALUES('Biblioteca Central',
'Calle Las Rosas #36, Col. La Sultana, Antiguo Cuscatlán','2243-5591',0.25,3,'T',67);

INSERT INTO EstadoProducto(stpEstado) VALUES('Disponible'),('En Proceso'),('Reservado'),('Coleccion Reserva'),('Prestamo'),('En Mantenimiento');

INSERT INTO Pais(paiAbrev,paiNombre) VALUES('AFG','Afganistán'),
('ALA','Islas de Åland'),
('ALB','Albania'),
('DZA','Argelia'),
('ASM','Samoa Americana'),
('AND','Andorra'),
('AGO','Angola'),
('AIA','Anguila'),
('ATA','Antártida'),
('ATG','Antigua y Barbuda'),
('ARG','Argentina'),
('ARM','Armenia'),
('ABW','Aruba'),
('AUS','Australia'),
('AUT','Austria'),
('AZE','Azerbaiyán'),
('BHS','Bahamas'),
('BHR','Baréin'),
('BGD','Bangladesh'),
('BRB','Barbados'),
('BLR','Bielorrusia'),
('BEL','Bélgica'),
('BLZ','Belice'),
('BEN','Benín'),
('BMU','Bermuda'),
('BTN','Bután'),
('BOL','Bolivia'),
('BES','Bonaire, San Eustaquio y Saba'),
('BIH','Bosnia y Herzegovina'),
('BWA','Botsuana'),
('BVT','Isla Bouvet'),
('BRA','Brasil'),
('IOT','Territorio Británico del Océano Índico'),
('VGB','Islas Vírgenes Británicas'),
('BRN','Brunei'),
('BGR','Bulgaria'),
('BFA','Burkina Faso'),
('BDI','Burundi'),
('KHM','Camboya'),
('CMR','Camerún'),
('CAN','Canadá'),
('CPV','Cabo Verde'),
('CYM','Islas Caimán'),
('CAF','República de África Central'),
('TCD','Chad'),
('CHL','Chile'),
('CHN','China'),
('CXR','Isla de Pascua'),
('CCK','Islas Cocos'),
('COL','Colombia'),
('COM','Comoras'),
('COK','Islas Cook'),
('CRI','Costa Rica'),
('HRV','Croacia'),
('CUB','Cuba'),
('CUW','Curazao'),
('CYP','Chipre'),
('CZE','República Checa'),
('COD','República Democrática del Congo'),
('DNK','Dinamarca'),
('DJI','Yibuti'),
('DMA','Dominica'),
('DOM','República Dominicana'),
('TLS','Timor Oriental'),
('ECU','Ecuador'),
('EGY','Egipto'),
('SLV','El Salvador'),
('GNQ','Guinea Ecuatorial'),
('ERI','Eritrea'),
('EST','Estonia'),
('ETH','Etiopía'),
('FLK','Islas Malvinas'),
('FRO','Islas Faroe'),
('FJI','Fiji'),
('FIN','Finlandia'),
('FRA','Francia'),
('GUF','Guayana Francesa'),
('PYF','Polinesia Francesa'),
('ATF','Territorios del sur Franceses'),
('GAB','Gabón'),
('GMB','Gambia'),
('GEO','Georgia'),
('DEU','Alemania'),
('GHA','Ghana'),
('GIB','Gibraltar'),
('GRC','Grecia'),
('GRL','Groenlandia'),
('GRD','Granada'),
('GLP','Guadalupe'),
('GUM','Guam'),
('GTM','Guatemala'),
('GGY','Guernsey'),
('GIN','Guinea'),
('GNB','Guinea Bissau'),
('GUY','Guyana'),
('HTI','Haití'),
('HMD','Islas Heard y McDonald'),
('HND','Honduras'),
('HKG','Hong Kong'),
('HUN','Hungría'),
('ISL','Islandia'),
('IND','India'),
('IDN','Indonesia'),
('IRN','Irán'),
('IRQ','Irak'),
('IRL','Irlanda'),
('IMN','Isla de Man'),
('ISR','Israel'),
('ITA','Italia'),
('CIV','Costa de Marfil'),
('JAM','Jamaica'),
('JPN','Japón'),
('JEY','Jersey'),
('JOR','Jordania'),
('KAZ','Kazajistán'),
('KEN','Kenia'),
('KIR','Kiribati'),
('XKX','Kosovo'),
('KWT','Kuwait'),
('KGZ','Kirguistán'),
('LAO','Laos'),
('LVA','Letonia'),
('LBN','Líbano'),
('LSO','Lesoto'),
('LBR','Liberia'),
('LBY','Libia'),
('LIE','Liechtenstein'),
('LTU','Lituania'),
('LUX','Luxemburgo'),
('MAC','Macao'),
('MKD','Macedonia'),
('MDG','Madagascar'),
('MWI','Malaui'),
('MYS','Malasia'),
('MDV','Maldivas'),
('MLI','Malí'),
('MLT','Malta'),
('MHL','Islas Marshall'),
('MTQ','Martinica'),
('MRT','Mauritania'),
('MUS','Mauricio'),
('MYT','Mayotte'),
('MEX','México'),
('FSM','Micronesia'),
('MDA','Moldavia'),
('MCO','Mónaco'),
('MNG','Mongolia'),
('MNE','Montenegro'),
('MSR','Montserrat'),
('MAR','Marruecos'),
('MOZ','Mozambique'),
('MMR','Myanmar'),
('NAM','Namibia'),
('NRU','Nauru'),
('NPL','Nepal'),
('NLD','Países Bajos'),
('ANT','Antillas Holandesas'),
('NCL','Nueva Caledonia'),
('NZL','Nueva Zelanda'),
('NIC','Nicaragua'),
('NER','Níger'),
('NGA','Nigeria'),
('NIU','Niue'),
('NFK','Isla Norfolk'),
('PRK','Corea del Norte'),
('MNP','Islas Marianas del Norte'),
('NOR','Noruega'),
('OMN','Omán'),
('PAK','Pakistán'),
('PLW','Palaos'),
('PSE','Territorios Palestinos'),
('PAN','Panamá'),
('PNG','Papúa Nueva Guinea'),
('PRY','Paraguay'),
('PER','Perú'),
('PHL','Filipinas'),
('PCN','Islas Pitcairn'),
('POL','Polonia'),
('PRT','Portugal'),
('PRI','Puerto Rico'),
('QAT','Catar'),
('COG','República del Congo'),
('REU','Reunión'),
('ROU','Rumanía'),
('RUS','Rusia'),
('RWA','Ruanda'),
('BLM','San Bartolomé'),
('SHN','Santa Elena'),
('KNA','San Cristóbal y Nieves'),
('LCA','Santa Lucía'),
('MAF','San Martín'),
('SPM','San Pedro y Miguelón'),
('VCT','San Vicente y las Granadinas'),
('WSM','Samoa Occidental'),
('SMR','San Marino'),
('STP','Santo Tomé y Príncipe'),
('SAU','Arabia Saudita'),
('SEN','Senegal'),
('SRB','Serbia'),
('SCG','Serbia y Montenegro'),
('SYC','Seychelles'),
('SLE','Sierra Leona'),
('SGP','Singapur'),
('SXM','San Martín'),
('SVK','Eslovaquia'),
('SVN','Eslovenia'),
('SLB','Islas Salomón'),
('SOM','Somalia'),
('ZAF','Sudáfrica'),
('SGS','Islas Georgia del Sur y Sandwich del Sur'),
('KOR','Corea del Sur'),
('SSD','Sudán del Sur'),
('ESP','España'),
('LKA','Sri Lanka'),
('SDN','Sudán'),
('SUR','Surinam'),
('SJM','Islas Svalbard y Jan Mayen'),
('SWZ','Suazilandia'),
('SWE','Suecia'),
('CHE','Suiza'),
('SYR','Siria'),
('TWN','Taiwán'),
('TJK','Tayikistán'),
('TZA','Tanzania'),
('THA','Tailandia'),
('TGO','República Togolesa'),
('TKL','Islas Tokelau'),
('TON','Tonga'),
('TTO','Trinidad y Tobago'),
('TUN','Túnez'),
('TUR','Turquía'),
('TKM','Turkmenistán'),
('TCA','Islas Turcos y Caicos'),
('TUV','Tuvalu'),
('VIR','Islas Vírgenes de los EE.UU.'),
('UGA','Uganda'),
('UKR','Ucrania'),
('ARE','Emiratos Árabes Unidos'),
('GBR','Reino Unido'),
('USA','Estados Unidos (USA)'),
('UMI','Islas menores alejadas de los Estados Unidos'),
('URY','Uruguay'),
('UZB','Uzbekistán'),
('VUT','Vanuatu'),
('VAT','Vaticano'),
('VEN','Venezuela'),
('VNM','Vietnam'),
('WLF','Wallis y Futuna'),
('ESH','Sahara Occidental'),
('YEM','Yemen'),
('ZMB','Zambia'),
('ZWE','Zimbabue');

INSERT INTO CategoriaProducto(cproCodigo,cproNombre,cproIdPrin) VALUES('000','Generalidades',NULL),
('001','Conocimiento',1),
('002','El libro',1),
('003','Sistemas',1),
('004','Procesamiento de datos. Ciencia de los computadores',1),
('005','Programación, programas, datos de computador',1),
('006','Métodos especiales de computador',1),
('007','',1),
('008','',1),
('009','',1),
('010','Bibliografía',1),
('011','Bibliografías',12),
('012','Bibliografías de individuos',12),
('013','De obras por categorías específicas de autores',12),
('014','De obras anónimas y seudónimas',12),
('015','De obras de lugares específicos',12),
('016','De obras sobre temas específicos',12),
('017','Catálogos generales por materia',12),
('018','Catálogos ordenados por autor, fecha, etc.',12),
('019','Catálogos diccionario',12),
('020','Bibliotecología y ciencias de la información',1),
('021','Relaciones bibliotecarias',23),
('022','Administracion de la planta física',23),
('023','Administración de personal',23),
('024','',23),
('025','Operaciones bibliotecarias',23),
('026','Bibliotecas para temas específicos',23),
('027','Bibliotecas generales',23),
('028','Lectura y uso de otros medios de información',23),
('029','',23),
('030','Obras enciclopédicas generales',1),
('031','Lengua inglesa norteamericana',32),
('032','En inglés',32),
('033','En otras lenguas germánicas',32),
('034','En francés, provenzal, catalán',32),
('035','En italiano, rumano, retorromano',32),
('036','En español y portugués',32),
('037','En lenguas eslavas',32),
('038','En lenguas escandinavas',32),
('039','En otras lenguas',32),
('040','',1),
('041','',42),
('049','',42),
('050','Publicaciones seriadas generales',1),
('051','Lengua inglesa norteamericana',45),
('052','En inglés',45),
('053','En otra lenguas germánicas',45),
('054','En francés , provenzal, catalán',45),
('055','En italiano, rumano, retorromano',45),
('056','En español y portugués',45),
('057','En lenguas eslavas',45),
('058','En lenguas escandinavas',45),
('059','En otras lenguas',45),
('060','Organizaciones generales y museología',1),
('061','En América del Norte',55),
('062','En las Islas Británicas En Inglaterra.',55),
('063','En Europa Central En Alemania',55),
('064','En Francía y Mónaco',55),
('065','En Italia y territorios adyacentes',55),
('066','En la Península Ibérica e islas adyacentes',55),
('067','En Europa  Oriental En Rusia',55),
('068','En otras áreas geográficas',55),
('069','Museología (Ciencia de los Museos)',55),
('070','Medios noticiosos, periodísmo, publicación',1),
('071','Periodismo y periódicos en América del Norte',65),
('072','En las Islas Británicas. En Inglaterra',65),
('073','En Europa Central. En Alemania',65),
('074','En Francía y Mónaco',65),
('075','En Italia y territorios adyacentes',65),
('076','En Península Ibérica e islas adyacentes',65),
('077','En Europa Oriental. En Rusia',65),
('078','En Escandinavia',65),
('079','En otras áreas geográficas',65),
('080','Colecciones generales',1),
('081','Lengua inglesa norteamericana',75),
('082','Colecciones generales en inglés',75),
('083','En otras lenguas germánicas',75),
('084','En francés, provenzal, catalán',75),
('085','En italiano, rumano, retorromano',75),
('086','En  español y portugués',75),
('087','En lenguas eslavas',75),
('088','En lenguas escandinavas',75),
('089','En lenguas itálicas, helénicas, otras lenguas',75),
('090','Manuscritos y libros raros',1),
('091','Manuscritos',85),
('092','Libros xilográficos',85),
('093','Incunables',85),
('094','Libros impresos',85),
('095','Libros notables por su encuadernación',85),
('096','Libros notables por las ilustraciones',85),
('097','Libros notables por su propietario u origen',85),
('098','Obras prohibidas, falsificaciones, imposturas',85),
('099','Libros notables por su formato',85),
('100','Filosofía y Psicología',NULL),
('101','Teoría de la filosofía',95),
('102','Miscelánea',95),
('103','Diccionarios y enciclopedias',95),
('104','',95),
('105','Publicaciones seriadas',95),
('106','Organizaciones y gerencia',95),
('107','Educación, investigación, temas relacionados',95),
('108','Tratamiento de clases de personas',95),
('109','Tratamiento histórico y colectivo de personas',95),
('110','Metafísica',95),
('111','Ontología',105),
('112','',105),
('113','Cosmología (Filosofía de la naturaleza)',105),
('114','Espacio',105),
('115','Tiempo',105),
('116','Cambio',105),
('117','Estructura',105),
('118','Fuerza y energía',105),
('119','Número y cantidad',105),
('120','Epistemología, causalidad, género humano',95),
('121','Epistemología (Teorìa del conocimiento)',115),
('122','Causalidad',115),
('123','Determinismo e indeterminismo',115),
('124','Teleología',115),
('125','',115),
('126','El yo',115),
('127','El inconsciente y el subconsciente',115),
('128','Género humano',115),
('129','Origen y destino de las almas individuales',115),
('130','Fenómenos paranormales',95),
('131','Métodos parapsicológicos y ocultos',125),
('132','',125),
('133','Parapsicología  y ocultismo',125),
('134','',125),
('135','Sueños y misterios',125),
('136','',125),
('137','Grafología adivinatoria',125),
('138','Fisionomía',125),
('139','Frenología',125),
('140','Escuelas filosóficas específicas',95),
('141','Idealismo y sistemas relacionados',135),
('142','Filosofía  crítica',135),
('143','Bergsonísmo e intuicionismo',135),
('144','Humanismo y sistemas relacionados',135),
('145','Sensacionalismo',135),
('146','Naturalismo y sistemas relacionados',135),
('147','Panteísmo y sistemas relacionados',135),
('148','Eclecticismo, liberalismo, tradicionalismo',135),
('149','Otros sistemas filosóficos',135),
('150','Psicología',95),
('151','',145),
('152','Percepción, movimiento emociones, impulsos',145),
('153','Procesos mentales e inteligencia',145),
('154','Subconsciente y estados alterados',145),
('155','Psicología diferencial y del desarrollo',145),
('156','Psicología comparada',145),
('157','',145),
('158','Psicología aplicada',145),
('159','',145),
('160','Lógica',95),
('161','Inducción',155),
('162','Deducción',155),
('163','',155),
('164','',155),
('165','Falacias y fuentes de error',155),
('166','Silogismos',155),
('167','Hipótesis',155),
('168','Argumento y persuasión',155),
('169','Analogía',155),
('170','Ética (Filosofía moral)',95),
('171','Sistemas éticos',165),
('172','Ética política',165),
('173','Ética de las relaciones familiares',165),
('174','Ética ocupacional',165),
('175','Ética de la recreación y del tiempo libre',165),
('176','Ética del sexo y la reproducción',165),
('177','Ética de las relaciones sociales',165),
('178','Ética del consumo',165),
('179','Otras normas éticas',165),
('180','Filosofía antigua , medieval, oriental',95),
('181','Filosofía oriental',175),
('182','Filosofías griegas presocráticas',175),
('183','Filosofías sofista y socrática',175),
('184','Filosofía platónica',175),
('185','Filosofía aristotélica',175),
('186','Filosofía escéptica y neoplatónica',175),
('187','Filosofía epicúrea',175),
('188','Filosofía estoica',175),
('189','Filosofía medieval occidental',175),
('190','Filosofía moderna occidental',95),
('191','Filosofía de Estados Unidos y Canadá',185),
('192','Filosofía de las Islas Británicas',185),
('193','Filosofía de Alemania y Austria',185),
('194','Filosofía de Francia',185),
('195','Filosofía de Italia',185),
('196','Filosofía de España y Portugal',185),
('197','Filosofía de la anterior Unión Soviética',185),
('198','Filosofía de Escandinavia',185),
('199','Filosofía de otras áreas geográficas',185),
('200','Religión',NULL),
('201','Subdivisiones comunes de la religión',195),
('210','Filosofía y teoría de la Religión',195),
('211','Conceptos de Dios',195),
('212','Existencia, sapiencia, atributos de Dios.',195),
('213','Creación',195),
('214','Teodicea',195),
('215','Ciencia y Religión',195),
('216','',195),
('217','',195),
('218','Género humano',195),
('219','',195),
('220','La Biblia',195),
('221','Antiguo Testamento (Tanakh)',207),
('222','Libros históricos del Antiguo Testamento',207),
('223','Libros poéticos del Antiguo Testamento',207),
('224','Libros proféticos del Antiguo Testamento',207),
('225','Nuevo Testamento',207),
('226','Evangelios y Hechos de los Apóstoles',207),
('227','Epístolas',207),
('228','Revelación (Apocalipsis)',207),
('229','Apócrifos y seudoepígrafes',207),
('230','Cristianismo Teología Cristiana',195),
('231','Dios',217),
('232','Jesucristo y su familia',217),
('233','Género humano',217),
('234','Salvación (soteriología y gracia)',217),
('235','Seres espirituales',217),
('236','Escatología',217),
('237','',217),
('238','Credos y catecismos',217),
('239','Apologética y polémicas',217),
('240','Moral cristiana y teología piadosa',195),
('241','Teología moral',227),
('242','Literatura piadosa',227),
('243','Escritos evangelizadores para individuos',227),
('244','',227),
('245','',227),
('246','Uso del arte en el cristianismo',227),
('247','Mobiliario y artículos eclesiásticos',227),
('248','Experiencia, práctica, vida cristianas',227),
('249','Observancias cristianas en la vida familiar',227),
('250','Órdenes cristianas e iglesia local',195),
('251','Predicación (Homilética)',237),
('252','Textos de sermones',237),
('253','Oficio pastoral (Teología pastoral)',237),
('254','Administración de la parroquia',237),
('255','Congregaciones y órdenes religiosas',237),
('256','',237),
('257','',237),
('258','',237),
('259','Atención pastoral de familias y de personas',237),
('260','Teología social y eclesiástica',195),
('261','Teología social',247),
('262','Eclesiología',247),
('263','Días, épocas, lugares de observancia',247),
('264','Culto público',247),
('265','Sacramentos, otros ritos  y ritos',247),
('266','Misiones',247),
('267','Asociaciones para trabajo religioso',247),
('268','Educación religiosa',247),
('269','Renovación espiritual',247),
('270','Historia del cristianismo y de la iglesia cristiana',195),
('271','Órdenes religiosas en la historia de la iglesia',257),
('272','Persecuciones en la historia de la iglesia',257),
('273','Controversias y herejías doctrinales',257),
('274','Historia del cristianismo en Europa',257),
('275','Historia del cristianismo en Asia',257),
('276','Historia del cristianismo en África',257),
('277','Historia del cristianismo en América del Norte',257),
('278','Historia del cristianismo en América del Sur',257),
('279','Historia del cristianismo en otras áreas',257),
('280','Confesiones y sectas cristianas',195),
('281','Iglesia temprana e iglesias orientales',267),
('282','Iglesia Católica Romana',267),
('283','Iglesias anglicanas',267),
('284','Protestantes de origen continental',267),
('285','Iglesias presbiterianas, reformadas, congregacionales',267),
('286','Iglesias bautistas, de los Discípulos de Cristo, adventistas',267),
('287','Iglesias metodistas y relacionadas',267),
('288','',267),
('289','Otras confesiones y sectas',267),
('290','Religión comparada y otras religiones',195),
('291','Religión comparada',277),
('292','Religión clásica (griega y romana)',277),
('293','Religión germánica',277),
('294','Religiones de origen índico',277),
('295','Zoroastrismo (Mazdeísmo, parsismo)',277),
('296','Judaísmo',277),
('297','Islamismo, babismo,fe bahai',277),
('298','',277),
('299','Otras religiones',277),
('300','Ciencias sociales',NULL),
('301','Sociología y antropología',287),
('302','Interacción social',287),
('303','Procesos sociales',287),
('304','Factores que afectan el comportamiento social',287),
('305','Grupos sociales',287),
('306','Cultura e instituciones',287),
('307','Comunidades',287),
('308','',287),
('309','',287),
('310','Colecciones de estadística general',287),
('311','',297),
('312','',297),
('313','',297),
('314','Estadísticas generales de Europa',297),
('315','Estadísticas generales de Asia',297),
('316','Estadísticas generales de África',297),
('317','Estadísticas generales de América del Norte',297),
('318','Estadísticas generales de América del Sur',297),
('319','Estadísticas generales de otras áreas',297),
('320','Ciencia política',287),
('321','Sistemas de gobiernos y de estados',307),
('322','Relación del estado con grupos organizados',307),
('323','Derechos civiles y políticos',307),
('324','El proceso político',307),
('325','Migración y colonización internacionales',307),
('326','Esclavitud y emancipación',307),
('327','Relaciones internacionales',307),
('328','El proceso legislativo',307),
('329','',307),
('330','Economía',287),
('331','Economía laboral',317),
('332','Economía financiera',317),
('333','Economía de la tierra y de la energía',317),
('334','Cooperativas',317),
('335','Socialismo y sistemas relacionados',317),
('336','Finanzas públicas',317),
('337','Economía internacional',317),
('338','Producción',317),
('339','Macroeconomía y temas relacionados',317),
('340','Derecho',287),
('341','Derecho internacional',327),
('342','Derecho constitucional y administrativo',327),
('343','Derecho militar, tributario, mercantil, industrial',327),
('344','Derecho laboral, social , educativo, cultural',327),
('345','Derecho penal',327),
('346','Derecho privado',327),
('347','Procedimiento y tribunales civiles',327),
('348','Leyes (Estatutos), reglamentaciones, jurisprudencia',327),
('349','Derecho de jurisdicciones y áreas específicas',327),
('350','Administración pública y ciencia militar',287),
('351','Administración pública',337),
('352','Consideraciones generales',337),
('353','Campos específicos de administración pública',337),
('354','Administración de la economía y del medio ambiente',337),
('355','Ciencia militar',337),
('356','Fuerzas y combate de infantería',337),
('357','Fuerzas y combate montados',337),
('358','Fuerzas aéreas y otras fuerzas especializadas',337),
('359','Fuerzas y combate marítimos (navales)',337),
('360','Problemas y servicios sociales; asociaciones',287),
('361','Problemas y bienestar sociales en general',347),
('362','Problemas y servicios de bienestar social',347),
('363','Otros problemas y servicios sociales',347),
('364','Criminología',347),
('365','Instituciones penales y relacionadas',347),
('366','Asociaciones',347),
('367','Clubes de carácter general',347),
('368','Seguros',347),
('369','Clases varias de asociaciones',347),
('370','Educación',287),
('371','Escuelas y actividades; educación especial',357),
('372','Educación primaria',357),
('373','Educación secundaria',357),
('374','Educación de adultos',357),
('375','Currículos',357),
('376','',357),
('377','',357),
('378','Educación superior',357),
('379','Asuntos de política pública en educación',357),
('380','Comercio , comunicaciones, transporte',287),
('381','Comercio interno (Comercio doméstico)',367),
('382','Comercio internacional (Comercio exterior)',367),
('383','Comunicación postal',367),
('384','Comunicaciones. Telecomunicación',367),
('385','Transporte ferroviario',367),
('386','Transporte por vía acuática interior y en transbordador',367),
('387','Transporte acuático , aéreo, espacial',367),
('388','Transporte. Transporte terrestre',367),
('389','Metrología y estandarización',367),
('390','Costumbres, etiqueta, folclore',287),
('391','Traje y apariencia personal',377),
('392','Costumbres del ciclo de vida y de la vida doméstica',377),
('393','Costumbres mortuorias',377),
('394','Costumbres generales',377),
('395','Etiquetas (Modales)',377),
('396','',377),
('397','',377),
('398','Folclore',377),
('399','Costumbres de guerra y diplomática',377),
('400','Lenguas',NULL),
('401','Filosofía y teoría',387),
('402','Miscelánea',387),
('403','Diccionarios y enciclopedias',387),
('404','Temas especiales',387),
('405','Publicaciones seriadas',387),
('406','Organizaciones y gerencia',387),
('407','Educación, investigacion, temas relacionados',387),
('408','Tratamiento de clases de personas',387),
('409','Tratamiento geográfico y de personas',387),
('410','Lingüística',387),
('411','Sistemas de escritura',397),
('412','Etimología',397),
('413','Diccionarios',397),
('414','Fonología y fonética',397),
('415','Gramática',397),
('416','',397),
('417','Dialectología y lingüística histórica',397),
('418','Uso estándar Lingüística aplicada',397),
('419','Lenguaje verbal no hablado ni escrito',397),
('420','Inglés e inglés antigüo',387),
('421','Sistemas de escritura y fonología ingleses',407),
('422','Etimología inglesa',407),
('423','Diccionarios de inglés',407),
('424','',407),
('425','Gramática inglesa',407),
('426','',407),
('427','Variaciones de la lengua inglesa',407),
('428','Uso del inglés estándar',407),
('429','Inglés antigüo (Anglosajón)',407),
('430','Lenguas germánicas.  Alemán',387),
('431','Sistemas de escritura y fonología alemanes',417),
('432','Etimología alemana',417),
('433','Diccionarios de alemán',417),
('434','',417),
('435','Gramática alemana',417),
('436','',417),
('437','Variaciones de la lengua alemana',417),
('438','Uso del alemán estándar',417),
('439','Otras lenguas germánicas',417),
('440','Lenguas romances. Francés',387),
('441','Sistemas de escritura y fonología franceses',427),
('442','Etimología francesa',427),
('443','Diccionarios de francés',427),
('444','',427),
('445','Gramática francesa',427),
('446','',427),
('447','Variaciones de la lengua francesa',427),
('448','Uso del francés estándar',427),
('449','Provenzal y catalán',427),
('450','Italiano, rumano, retorromano',387),
('451','Sistema de escritura y fonología italianos',437),
('452','Etimología italiana',437),
('453','Diccionario de italiano',437),
('454','',437),
('455','Gramática italiana',437),
('456','',437),
('457','Variaciones de la lengua italiana',437),
('458','Uso del italiano estándar',437),
('459','Rumano y retorromano',437),
('460','Lenguas española y portuguesa',387),
('461','Sistemas de escritura y fonología españoles',447),
('462','Etimología española',447),
('463','Diccionario de español',447),
('464','',447),
('465','Gramática española',447),
('466','',447),
('467','Variaciones de la lengua española',447),
('468','Uso del español estándar',447),
('469','Portugués',447),
('470','Lenguas itálicas. Latín',387),
('471','Escritura y fonología latinas clásicas',457),
('472','Etimología latina clásica',457),
('473','Diccionarios de latín clásico',457),
('474','',457),
('475','Gramática latina clásica',457),
('476','',457),
('477','Latín antiguo, posclásico, vulgar',457),
('478','Uso del latín clásico',457),
('479','Otras lenguas itálicas',457),
('480','Lenguas helénicas. Griego clásico',387),
('481','Escritura y fonología griegas clásicas',467),
('482','Etimología griega clásica',467),
('483','Diccionarios de griego clásico',467),
('484','',467),
('485','Gramática griega clásica',467),
('486','',467),
('487','Griego preclásico y posclásico',467),
('488','Uso del griego clásico',467),
('489','Otras lenguas helénicas',467),
('490','Otras lenguas',387),
('491','Lenguas indoeuropeas orientales y célticas',477),
('492','Lenguas afroasiáticas. Semíticas',477),
('493','Lenguas afroasiáticas no semíticas',477),
('494','Lenguas altaicas, urálicas, hiperbóreas, dravídicas',477),
('495','Lenguas del Asia oriental y sudoriental',477),
('496','Lenguas africanas',477),
('497','Lenguas nativas norteamericanas',477),
('498','Lenguas nativas sudamericanas',477),
('499','Lenguas austronesias y otras',477),
('500','Ciencias naturales y matemáticas',NULL),
('501','Filosofía y teoría',487),
('502','Miscelánea',487),
('503','Diccionarios y enciclopedias',487),
('504','',487),
('505','Publicaciones seriadas',487),
('506','Organización  y gerencia',487),
('507','Educación, investigación, temas relacionados',487),
('508','Historia natural',487),
('509','Tratamiento histórico , geográfico , de personas',487),
('510','Matemáticas',487),
('511','Principios generales de las matemáticas',497),
('512','Álgebra, teoría de los números',497),
('513','Aritmética',497),
('514','Topología',497),
('515','Análisis',497),
('516','Geometría',497),
('517','',497),
('518','',497),
('519','Probabilidades y matemáticas aplicadas',497),
('520','Astronomía y ciencias afines',487),
('521','Mecánica celeste',507),
('522','Técnicas , equipo, materiales',507),
('523','Cuerpos y fenómenos celestes específicos',507),
('524','',507),
('525','La tierrra (Geografía astronómica)',507),
('526','Geografía matemática',507),
('527','Navegación celeste',507),
('528','Efemérides',507),
('529','Cronología',507),
('530','Física',487),
('531','Mecánica clásica. Mecánica de sólidos',517),
('532','Mecánica de fluidos. Mecánica de líquidos',517),
('533','Neumática (Mecánica de gases)',517),
('534','Sonido y vibraciones relacionadas',517),
('535','Luz y fenómenos parafóticos',517),
('536','Calor',517),
('537','Electricidad y electrónica',517),
('538','Magnetismo',517),
('539','Física moderna',517),
('540','Química y ciencias afines',487),
('541','Química física y teórica',527),
('542','Técnicas, equipo, materiales',527),
('543','Química analítica',527),
('544','Análisis cualitativo',527),
('545','Análisis cuantitativo',527),
('546','Química inorgánica',527),
('547','Química orgánica',527),
('548','Cristalografía',527),
('549','Mineralogía',527),
('550','Ciencias de la tierra',487),
('551','Geología, hidrología, meteorología',537),
('552','Petrología',537),
('553','Geología económica',537),
('554','Ciencias de la tierra de Europa',537),
('555','Ciencias de la tierra de Asia',537),
('556','Ciencias de la tierra de África',537),
('557','Ciencias de la tierra de América del Norte',537),
('558','Ciencias de la tierra de América del Sur',537),
('559','Ciencias de la tierra de otras áreas',537),
('560','Paleontología. Paleozoología',487),
('561','Paleobotánica; microorganismos fósiles',547),
('562','Invertebrados fósiles',547),
('563','Otros invertebrados fósiles',547),
('564','Mollusca (Moluscos) y Molluscoidea (Moluscoideos) fósiles',547),
('565','Arthropoda (Artrópodos) fósiles',547),
('566','Chordata (Cordados) fósiles',547),
('567','Vertebrados fósiles de sangre fría',547),
('568','Aves (Pájaros) fósiles',547),
('569','Mammalia (Mamíferos) fósiles',547),
('570','Ciencias de la vida. Biología',487),
('571','Fisiología y temas relacionados',557),
('572','Bioquímica',557),
('573','Sistemas específicos en animales',557),
('574','',557),
('575','Partes específicas de y sistemas en plantas',557),
('576','Genética y evolución',557),
('577','Ecología',557),
('578','Historia natural de los organismos',557),
('579','Microorganismos, hongos, algas',557),
('580','Plantas',487),
('581','Temas específicos en historia natural',567),
('582','Plantas destacadas por características y flores',567),
('583','Magnoliosida (Dicotiledóneas)',567),
('584','Liliopsida (Monocotiledóneas)',567),
('585','Pinophyta (Gimnospermas). Coniferales (Coníferas)',567),
('586','Cryptogamia (Criptógamas, Plantas sin semillas)',567),
('587','Pteridophyta (Pteridofitas, Plantas vasculares sin semillas)',567),
('588','Bryophyta (Briofitas)',567),
('589','',567),
('590','Animales',487),
('591','Temas específicos en historia natural',577),
('592','Invertebrados',577),
('593','Invertebrados marinos y del litoral',577),
('594','Mollusca (Moluscos) y Molluscoidea (Moluscoideos)',577),
('595','Arthropoda (Artrópodos)',577),
('596','Chordata (Cordados)',577),
('597','Vertebrados de sangre fría. Pisces (Peces)',577),
('598','Aves (Pájaros)',577),
('599','Mammalia (Mamíferos)',577),
('600','Tecnología (Ciencias aplicadas)',NULL),
('601','Filosofía y teoría',587),
('602','Miscelánea',587),
('603','Diccionarios y enciclopedias',587),
('604','Temas especiales',587),
('605','Publicaciones seriadas',587),
('606','Organizaciones',587),
('607','Educación, investigación, temas relacionados',587),
('608','Invenciones y patentes',587),
('609','Tratamiento histórico, geográfico de personas',587),
('610','Ciencias médicas. Medicina',587),
('611','Anatomía humana, citología, histología',597),
('612','Fisiología humana',597),
('613','Promoción de la salud',597),
('614','Incidencia y prevención de la enfermedad',597),
('615','Farmacología y terapéutica',597),
('616','Enfermedades',597),
('617','Cirugía y especialidades médicas relacionadas',597),
('618','Ginecología y otras especialidades médicas',597),
('619','Medicína experimental',597),
('620','Ingeniería y operaciones afines',587),
('621','Física aplicada',607),
('622','Minería y operaciones relacionadas',607),
('623','Ingeniería militar y náutica',607),
('624','Ingeniería civil',607),
('625','Ingeniería de ferrocarriles y de carretera',607),
('626','',607),
('627','Ingeniería hidráulica',607),
('628','Ingeniería sanitaria y municipal',607),
('629','Otras ramas de la ingeniería',607),
('630','Agricultura y tecnologías relacionadas',587),
('631','Técnicas, equipo, materiales',617),
('632','Lesiones, enfermedades, plagas vegetales',617),
('633','Cultivos de campo y de plantación',617),
('634','Huertos, frutas, silvicultura',617),
('635','Cultívos hortículas (Horticultura)',617),
('636','Producción animal (Zootecnia)',617),
('637','Procesamiento lechero y productos relacionados',617),
('638','Cultivo de insectos',617),
('639','Caza, pesca, conservación',617),
('640','Economía doméstica y vida familiar',587),
('641','Alimentos y bebidas',627),
('642','Comidas y servicios a la mesa',627),
('643','Vivienda y equipo de la casa',627),
('644','Servicios de la casa',627),
('645','Dotaciones de la casa',627),
('646','Costura, vestuario, vida personal',627),
('647','Gerencia de viviendas públicas',627),
('648','Cuidado de la casa',627),
('649','Crianza de niños y atención domiciliaria de personas',627),
('650','Gerencia y servicios auxiliares',587),
('651','Servicios de oficina',637),
('652','Procesos de comunicación escrita',637),
('653','Taquigrafía',637),
('654','',637),
('655','',637),
('656','',637),
('657','Contabilidad',637),
('658','Gerencia general',637),
('659','Publicidad',637),
('660','Ingeniería química',587),
('661','Tecnología de químicos industriales',647),
('662','Explosivos, combustibles, productos relacionados',647),
('663','Tecnología de bebidas',647),
('664','Tecnología de alimentos',647),
('665','Aceites, grasas, ceras, gases industriales',647),
('666','Cerámica y tecnologías afines',647),
('667','Tecnología de la limpieza, del color, del revestimiento',647),
('668','Tecnología de otros productos orgánicos',647),
('669','Metalurgia',647),
('670','Manufactura',587),
('671','Metalistería y productos metálicos',657),
('672','Hierro, acero, otras aleaciones ferrosas',657),
('673','Metales no ferrosos',657),
('674','Procesamiento de madera aserrada, productos de madera, corchos',657),
('675','Procesamiento del cuero y de la piel',657),
('676','Tecnología de la pulpa y del papel',657),
('677','Textiles',657),
('678','Elastómeros y productos elastoméricos',657),
('679','Otros productos de materiales específicos',657),
('680','Manufactura para usos específicos',587),
('681','Instrumentos de precisión y otros dispositivos',667),
('682','Trabajo de forja pequeña (Herrería)',667),
('683','Ferretería y aparatos de la casa',667),
('684','Muebles y talleres de hogar',667),
('685','Artículos de cuero, de piel, productos relacionados',667),
('686','Imprenta y actividades relacionadas',667),
('687','Vestuario y accesorios',667),
('688','Otros productos acabados y empaques',667),
('689','',667),
('690','Construcción',587),
('691','Materiales de construcción',677),
('692','Prácticas auxiliares de construcción',677),
('693','Materiales y propósitos específicos',677),
('694','Construcción en madera Carpintería',677),
('695','Cubiertas para techos',677),
('696','Servicios públicos',677),
('697','Calefacción, ventilación, aire acondicionado',677),
('698','Acabado detallado',677),
('699','',677),
('700','Las artes. Bellas artes y artes decorativas',NULL),
('701','Filosofía de las bellas artes y artes decorativas',687),
('702','Miscelánea de las bellas artes y artes decorativas',687),
('703','Diccionarios de las bellas artes y artes decorativas',687),
('704','Temas especiales de las bellas artes y artes decorativas',687),
('705','Publicaciones seriadas de las bellas artes y artes decorativas',687),
('706','Organizaciones y gerencia',687),
('707','Educación, investigación, temas relacionados',687),
('708','Galerías, museos, colecciones privadas',687),
('709','Tratamiento histórico, geográfico, de personas',687),
('710','Urbanismo y arte paisajístico',687),
('711','Planificación del espacio (Urbanismo)',697),
('712','Arquitectura paisajística',697),
('713','Arquitectura paisajística de las vías de tráfico',697),
('714','Elementos acuáticos',697),
('715','Plantas leñosas',697),
('716','Plantas herbáceas',697),
('717','Estructuras en arquitectura paisajística',697),
('718','Diseño paisajístico de cementerios',697),
('719','Paisajes naturales',697),
('720','Arquitectura',687),
('721','Estructura arquitectónica',707),
('722','Arquitectura hasta ca. 300',707),
('723','Arquitectura desde ca. 300 hasta 1399',707),
('724','Arquitectura desde 1400',707),
('725','Estructuras públicas',707),
('726','Edificios para propósitos religiosos',707),
('727','Edificios para educación e investigación',707),
('728','Edificios residenciales y relacionados',707),
('729','Diseño y decoración',707),
('730','Artes plásticas. Escultura',687),
('731','Procesos, formas, temas de la escultura',717),
('732','Escultura hasta ca. 500',717),
('733','Escultura griega, etrusca, romana',717),
('734','Escultura desde ca. 500 hasta 1399',717),
('735','Escultura desde 1400',717),
('736','Talla y tallados',717),
('737','Numismática y sigilografía',717),
('738','Artes cerámicas',717),
('739','Metalistería artística',717),
('740','Dibujo y artes  decorativas',687),
('741','Dibujo y dibujos',727),
('742','Perspectiva',727),
('743','Dibujo y dibujos por tema',727),
('744','',727),
('745','Artes decorativas',727),
('746','Artes textiles',727),
('747','Decoración de interiores',727),
('748','Vidrio',727),
('749','Muebles y accesorios',727),
('750','Pintura y pinturas',687),
('751','Técnicas, equipo, materiales, formas',737),
('752','Color',737),
('753','Simbolismo, alegoría, mitología, leyenda',737),
('754','Pintura de género',737),
('755','Religión',737),
('756','',737),
('757','Figuras humanas',737),
('758','Otros temas',737),
('759','Tratamiento histórico, geográfico, de personas',737),
('760','Artes gráficas. Arte de grabar y grabados',687),
('761','Procesos en relieve (impresión de planchas de madera)',747),
('762','',747),
('763','Procesos litográficos (planográficos)',747),
('764','Cromolitografía y serigrafía',747),
('765','Grabado en metal',747),
('766','Media tinta, aguatinta, procesos relacionados',747),
('767','Aguafuerte, grabados a punta seca',747),
('768','',747),
('769','Grabados',747),
('770','Fotografía y fotografías',687),
('771','Técnicas, equipo y materiales',757),
('772','Procesos con sales metálicas',757),
('773','Procesos de pigmentación de la impresión',757),
('774','Holografía',757),
('775','',757),
('776','',757),
('777','',757),
('778','Campos y clases de fotografía',757),
('779','Fotografías',757),
('780','Música',687),
('781','Principios generales y formas musicales',767),
('782','Música vocal',767),
('783','Música para voces individuales La voz',767),
('784','Instrumentos y conjuntos instrumentales',767),
('785','Conjuntos con un solo instrumento por parte',767),
('786','Instrumentos de teclado y otros',767),
('787','Instrumentos de cuerda (Cordófonos)',767),
('788','Instrumentos de viento (Acrófonos)',767),
('789','',767),
('790','Artes recreativas y de la actualización',687),
('791','Representaciones públicas',777),
('792','Presentaciones escénicas',777),
('793','Juegos y diversiones bajo techo',777),
('794','Juegos de destreza bajo techo',777),
('795','Juegos de suerte',777),
('796','Deportes y juegos atléticos y al aire libre',777),
('797','Deportes acuáticos y aéreos',777),
('798','Deportes ecuestres y carreras de animales',777),
('799','Pesca, caza, tiro',777),
('800','Literatura y retórica',NULL),
('801','Filosofía y teoría',787),
('802','Miscelánea',787),
('803','Diccionarios y enciclopedias',787),
('804','',787),
('805','Publicaciones seriadas',787),
('806','Organizaciones y gerencia',787),
('807','Educación, investigación, temas relacionados',787),
('808','Retórica y colecciones de literatura',787),
('809','Historia, descripción, crítica',787),
('810','Literatura norteamericana en inglés',787),
('811','Poesía norteamericana en inglés',797),
('812','Teatro norteamericano en inglés',797),
('813','Novelística norteamericana en inglés',797),
('814','Ensayos norteamericanos en inglés',797),
('815','Discursos norteamericanos en inglés',797),
('816','Cartas norteamericanas en inglés',797),
('817','Humor y sátira norteamericanos en inglés',797),
('818','Escritos varios norteamericanos',797),
('819','',797),
('820','Literatura inglesa e inglesa antigua',787),
('821','Poesía inglesa',807),
('822','Teatro inglés',807),
('823','Novelística inglesa',807),
('824','Ensayos ingleses',807),
('825','Discursos ingleses',807),
('826','Cartas inglesas',807),
('827','Humor y sátira ingleses',807),
('828','Escritos varios ingleses',807),
('829','Literatura inglesa antigüa (anglosajona)',807),
('830','Literatura de las lenguas germánicas',787),
('831','Poesía alemana',817),
('832','Teatro alemán',817),
('833','Novelística alemana',817),
('834','Ensayos alemanes',817),
('835','Discursos alemanes',817),
('836','Cartas alemanas',817),
('837','Humor y sátira alemanes',817),
('838','Escritos varios alemanes',817),
('839','Otras literaturas germánicas',817),
('840','Literatura de las lenguas romances',787),
('841','Poesía francesa',827),
('842','Teatro francés',827),
('843','Novelística francesa',827),
('844','Ensayos franceses',827),
('845','Discursos franceses',827),
('846','Cartas francesas',827),
('847','Humor y sátira franceses',827),
('848','Escritos varios franceses',827),
('849','Literaturas provenzal y catalana',827),
('850','Literaturas italiana, rumana, retorromana',787),
('851','Poesía italiana',837),
('852','Teatro italiano',837),
('853','Novelística italiana',837),
('854','Ensayos italianos',837),
('855','Discursos italianos',837),
('856','Cartas italianas',837),
('857','Humor y sátira italianos',837),
('858','Escritos varios italianos',837),
('859','Literatura portuguesa',837),
('860','Literatura española y portuguesa',787),
('861','Poesía española',847),
('862','Teatro español',847),
('863','Novelística española',847),
('864','Ensayos españoles',847),
('865','Discursos españoles',847),
('866','Cartas españolas',847),
('867','Humor y sátira españoles',847),
('868','Escritos varios españoles',847),
('869','Literatura portuguesa',847),
('870','Literaturas itálicas. Literatura latina',787),
('871','Poesía latina',857),
('872','Poesía y teatro dramáticos latinos',857),
('873','Poesía y novelística épicas latinas',857),
('874','Poesía lírica latina',857),
('875','Discursos latinos',857),
('876','Cartas latinas',857),
('877','Humor y sátira latinos',857),
('878','Escritos varios latinos',857),
('879','Literaturas de otras lenguas itálicas',857),
('880','Literaturas helénicas. Literatura griega clásica',787),
('881','Poesía griega clásica',867),
('882','Poesía y teatro dramáticos griegos clásicos',867),
('883','Poesía y novelística épicas griegas clásicas',867),
('884','Poesía lírica griega clásica',867),
('885','Discursos griegos clásicos',867),
('886','Cartas griegas clásicas',867),
('887','Humor y sátira griegos clásicos',867),
('888','Escritos varios griegos clásicos',867),
('889','Literatura griega moderna',867),
('890','Literaturas de otras lenguas',787),
('891','Indoeuropeas, orientales y célticas',877),
('892','Afroasiáticas. Semíticas',877),
('893','Afroasiáticas no semíticas',877),
('894','Altaicas, urálicas, hiperbóleas, dravídicas',877),
('895','Del Asia oriental y sudoriental',877),
('896','Africanas',877),
('897','Nativas norteamericanas',877),
('898','Nativas sudamericanas',877),
('899','Austronesias y otras',877),
('900','Geografía e historia',NULL),
('901','Filosofía y teoría',887),
('902','Miscelánea',887),
('903','Diccionarios y enciclopedias',887),
('904','Relatos colectivos de acontecimientos',887),
('905','Publicaciones seriadas',887),
('906','Organizaciones y gerencia',887),
('907','Educación, investigación, temas relacionados',887),
('908','Tratamiento de clases de personas',887),
('909','Historia universal',887),
('910','Geografía y viajes',887),
('911','Geografía histórica',897),
('912','Representaciones gráficas',897),
('913','Geografía de y viajes en el mundo antiguo',897),
('914','Geografía de y viajes en Europa',897),
('915','Geografía de y viajes en Asia',897),
('916','Geografía de y viajes en África',897),
('917','Geografía de y viajes en América del Norte',897),
('918','Geografía de y viajes en América del Sur',897),
('919','Geografía de y viajes en otras áreas',897),
('920','Biografía, genealogía, insignias',887),
('921','',907),
('922','',907),
('923','',907),
('924','',907),
('925','',907),
('926','',907),
('927','',907),
('928','',907),
('929','Biografía, nombres, insignias',907),
('930','Historia del mundo antiguo hasta ca. 499',887),
('931','China hasta 420',917),
('932','Egipto hasta 640',917),
('933','Palestina hasta 70',917),
('934','India hasta 647',917),
('935','Mesopotamia y Meseta Iraní hasta 637',917),
('936','Europa al norte y al occidente de Italia hasta ca. 499',917),
('937','Italia y territorios adyacentes hasta 476',917),
('938','Grecia hasta 323',917),
('939','Otras partes del mundo antiguo hasta 640',917),
('940','Historia general de Europa',887),
('941','Islas Británicas',927),
('942','Inglaterra y Gales',927),
('943','Europa central. Alemania',927),
('944','Francia y Mónaco',927),
('945','Península Itálica e islas adyacentes',927),
('946','Península Ibérica e islas adyacentes',927),
('947','Europa Oriental. Rusia',927),
('948','Escandinavia',927),
('949','Otras partes de Europa',927),
('950','Historia general de Asia. Lejano Oriente',887),
('951','China y áreas adyacentes',937),
('952','Japón',937),
('953','Península de Arabia y áreas adyacentes',937),
('954','Asia del Sur. India',937),
('955','Irán',937),
('956','Medio Oriente (Cercano Oriente)',937),
('957','Siberia (Rusia asiática)',937),
('958','Asia Central',937),
('959','Asia Sudoriental',937),
('960','Historia general de África',887),
('961','Túnez y Libia',947),
('962','Egipto y Sudán',947),
('963','Etiopía y Eritrea',947),
('964','Costa noroccidental africana e islas cercanas',947),
('965','Argelia',947),
('966','África occidental e islas cercanas',947),
('967','África central e islas cercanas',947),
('968','África del Sur. República de Sudáfrica',947),
('969','Islas del Oceáno Índico Sur',947),
('970','Historia general de América del Norte',887),
('971','Canadá',957),
('972','Mesoamérica (América Media) México',957),
('973','Estados Unidos',957),
('974','Nororiente de Estados Unidos',957),
('975','Sudoriente de Estados Unidos',957),
('976','Centro-sur de Estados Unidos',957),
('977','Centro-norte de Estados Unidos',957),
('978','Occidente de Estados Unidos',957),
('979','Región de la Gran Cuenca y de la Vertiente del Pacífico',957),
('980','Historia general de América del Sur',887),
('981','Brasil',967),
('982','Argentina',967),
('983','Chile',967),
('984','Bolivia',967),
('985','Perú',967),
('986','Colombia y Ecuador',967),
('987','Venezuela',967),
('988','Guayanas',967),
('989','Paraguay y Uruguay',967),
('990','Historia general de otras áreas',887),
('991','',978),
('992','',978),
('993','Nueva Zelanda',978),
('994','Australia',978),
('995','Melanesia. Nueva Guinea',978),
('996','Otras partes del Océano Pacífico Polinesia',978),
('997','Islas del Océano Atlántico',978),
('998','Islas árticas y Antártida',978),
('999','Mundos extraterrestres',978);
